User specified number of significant figures for numerical outputs
pymc-labs/CausalPy pull request #283
Opened 2023-12-22 16:27 UTC by drbenvincent

* Closes #282 
* Doctests and tests pass locally.
* Docstrings updated to reflect the new output you get.

2023-12-22 16:47 UTC, drbenvincent commented
Pfft. These doctests are brittle.

2023-12-24 18:57 UTC, jpreszler commented
There are definitely some that are particularly problematic, and will continue to be so without some significant changes. I think the value comes over the long-term, but it will be hard to get there without some improvements. The options I see:
1. turn them off, at least temporarily.
2. Split the example and output into separate docstrings (could be difficult for some longer examples). This would flag the biggest problems (an exception from input changes) but would make the actual example output static. This could be a good temporary fix in some places.
3. Replace the more problematic examples. I generally grabbed things from the other docs which are nice realistic example but have coefficients near 0 or HDI's near or including 0. This is perhaps the biggest issue since the output may change sign in a way the makes even the pytest numeric accuracy checks too strict. It's likely possible to have examples that show the right output, but sacrifice realism for basic numeric stability that make the doctests far more reliable. 

My vote would be to temporarily turn off the tests and replace the examples for at least PrePostFit (flakey), RegressionDiscontinuity (flakey) and the Instrumented Variables (slow) and turn doctests back on. I should be able to work on this soon, perhaps even getting better examples over the next week.

2023-12-24 19:04 UTC, jpreszler commented
created https://github.com/pymc-labs/CausalPy/issues/284. For now, I think you can just comment out the doctest call in the CI untill that issue is resolved.

2024-01-05 11:57 UTC, drbenvincent commented
Note to self: I'll finish and merge this PR after #286 is merged

2024-01-05 21:24 UTC, drbenvincent commented
Well, I guess I have to increase test coverage

2024-01-08 21:44 UTC, juanitorduz requested changes
Minor change request ;) Otherwise LGTM.

2024-01-08 21:44 UTC, juanitorduz commented on causalpy/pymc_experiments.py
> +            Number of decimals used to round results. Defaults to 2. Use "none" to return raw numbers.
None (upper case)

2024-01-08 21:44 UTC, juanitorduz commented on causalpy/pymc_experiments.py
> +            Number of decimals used to round results. Defaults to 2. Use "none" to return raw numbers.
None (upper case)

2024-02-05 13:23 UTC, drbenvincent commented on causalpy/pymc_experiments.py
> +            Number of decimals used to round results. Defaults to 2. Use "none" to return raw numbers.
Done: changed this for all instances

2024-02-05 13:23 UTC, merged